view:
  participants:
    pageSize: 10
  competitions:
    general:
      pageSize: 5
    detailed:
      pageSize: 3

# Notification settings
notification:
  mode: BOTH  # LEGACY, AGGREGATED, or BOTH
  onlyForAdmin: true
  processor:
    cron-pattern: "0 15,45 6,10,14,18,22 * * *"
  aggregated:
    enabled: true
    cleanupAfterDays: 7
    minutesThreshold: 60

logging:
  file:
    name: ./logs/file.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
